-- ---------------------------------------------------------------------------
-- CRM de Ryu Ads · esquema para integrarlo en un ERP existente
--
-- Escrito para PostgreSQL. Para MySQL/MariaDB: cambia GENERATED ... IDENTITY
-- por AUTO_INCREMENT, TIMESTAMPTZ por DATETIME y quita el "IF NOT EXISTS" de
-- los índices si tu versión no lo admite.
--
-- Prefijo crm_ en todas las tablas para que convivan con las del ERP sin
-- colisionar. La única que toca lo tuyo es crm_oportunidades.cliente_id.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Etapas del embudo.
--
-- Va en tabla y no como constante en el código a propósito: la probabilidad de
-- cierre hay que ajustarla con tus datos reales cada pocos meses, y eso no
-- debería obligarte a desplegar. Los valores de abajo son el estándar del
-- sector; sustitúyelos en cuanto tengas 20-30 operaciones cerradas.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_etapas (
  id           TEXT PRIMARY KEY,
  nombre       TEXT    NOT NULL,
  probabilidad NUMERIC(4,3) NOT NULL CHECK (probabilidad BETWEEN 0 AND 1),
  es_abierta   BOOLEAN NOT NULL DEFAULT TRUE,
  orden        INT     NOT NULL
);

INSERT INTO crm_etapas (id, nombre, probabilidad, es_abierta, orden) VALUES
  ('nuevo',       'Nuevo',       0.10, TRUE,  1),
  ('contactado',  'Contactado',  0.20, TRUE,  2),
  ('reunion',     'Reunión',     0.40, TRUE,  3),
  ('propuesta',   'Propuesta',   0.60, TRUE,  4),
  ('negociacion', 'Negociación', 0.80, TRUE,  5),
  ('ganado',      'Ganado',      1.00, FALSE, 6),
  ('perdido',     'Perdido',     0.00, FALSE, 7)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Oportunidades.
--
-- cliente_id es NULL mientras es un lead: todavía no es cliente de la agencia
-- y no tiene por qué existir en la tabla de clientes del ERP. Al pasar la
-- oportunidad a 'ganado' es cuando se crea el cliente y se rellena aquí. Ese
-- es el punto exacto donde el CRM se enchufa al ERP.
--
-- Los datos de contacto se guardan aquí duplicados a propósito: un lead que
-- nunca llega a cliente no debe ensuciar tu maestro de clientes.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_oportunidades (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id     BIGINT REFERENCES clientes(id) ON DELETE SET NULL,

  empresa        TEXT NOT NULL,
  contacto       TEXT NOT NULL DEFAULT '',
  email          TEXT NOT NULL DEFAULT '',
  telefono       TEXT NOT NULL DEFAULT '',

  servicio       TEXT NOT NULL,
  origen         TEXT NOT NULL,
  etapa          TEXT NOT NULL REFERENCES crm_etapas(id),

  -- Separados porque no valen lo mismo: 500 €/mes recurrentes no son 500 € una vez.
  cuota_mensual  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (cuota_mensual >= 0),
  pago_unico     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (pago_unico    >= 0),

  fecha_alta     DATE NOT NULL DEFAULT CURRENT_DATE,

  -- El par que convierte esto en un CRM y no en una agenda de contactos.
  proxima_accion TEXT NOT NULL DEFAULT '',
  proxima_fecha  DATE,

  motivo_perdida TEXT NOT NULL DEFAULT '',
  notas          TEXT NOT NULL DEFAULT '',

  -- Se sella al cambiar de etapa a una cerrada. Si se dedujera del último
  -- apunte del historial, añadir una nota vieja movería el "ganado este mes".
  cerrada_en     DATE,

  creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Una oportunidad cerrada tiene fecha de cierre; una abierta, no.
  CONSTRAINT crm_cierre_coherente CHECK (
    (etapa IN ('ganado','perdido') AND cerrada_en IS NOT NULL) OR
    (etapa NOT IN ('ganado','perdido') AND cerrada_en IS NULL)
  )
);

-- El listado por defecto es "abiertas ordenadas por fecha de seguimiento".
CREATE INDEX IF NOT EXISTS crm_op_seguimiento_idx ON crm_oportunidades (proxima_fecha)
  WHERE etapa NOT IN ('ganado','perdido');
CREATE INDEX IF NOT EXISTS crm_op_etapa_idx   ON crm_oportunidades (etapa);
CREATE INDEX IF NOT EXISTS crm_op_cliente_idx ON crm_oportunidades (cliente_id);
CREATE INDEX IF NOT EXISTS crm_op_cierre_idx  ON crm_oportunidades (cerrada_en);

-- ---------------------------------------------------------------------------
-- Historial. Los cambios de etapa se registran solos; las llamadas y emails
-- los escribes tú. Es la memoria que te salva tres semanas después.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_actividades (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oportunidad_id BIGINT NOT NULL REFERENCES crm_oportunidades(id) ON DELETE CASCADE,
  fecha          DATE NOT NULL DEFAULT CURRENT_DATE,
  tipo           TEXT NOT NULL DEFAULT 'nota'
                 CHECK (tipo IN ('nota','etapa','llamada','email','reunion')),
  texto          TEXT NOT NULL,
  creado_en      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_act_oportunidad_idx
  ON crm_actividades (oportunidad_id, fecha DESC);

-- ---------------------------------------------------------------------------
-- Vista de seguimiento: lo que te toca hacer hoy, con su urgencia ya calculada.
-- Es la consulta que alimenta la pantalla principal.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW crm_seguimiento AS
SELECT
  o.id,
  o.empresa,
  o.contacto,
  o.etapa,
  e.nombre AS etapa_nombre,
  o.proxima_accion,
  o.proxima_fecha,
  o.cuota_mensual,
  CASE
    WHEN o.proxima_fecha IS NULL                       THEN 'sin_seguimiento'
    WHEN o.proxima_fecha <  CURRENT_DATE               THEN 'vencida'
    WHEN o.proxima_fecha =  CURRENT_DATE               THEN 'hoy'
    WHEN o.proxima_fecha <= CURRENT_DATE + INTERVAL '7 day' THEN 'semana'
    ELSE 'despues'
  END AS urgencia
FROM crm_oportunidades o
JOIN crm_etapas e ON e.id = o.etapa
WHERE e.es_abierta;

-- ---------------------------------------------------------------------------
-- Métricas del panel. MESES_CONTRATO = 12 es una asunción: si tus contratos
-- duran menos, la previsión ponderada te mentirá hacia arriba.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW crm_metricas AS
SELECT
  (SELECT COALESCE(SUM(o.cuota_mensual),0)
     FROM crm_oportunidades o JOIN crm_etapas e ON e.id=o.etapa
    WHERE e.es_abierta)                                        AS pipeline_mensual,
  (SELECT COUNT(*)
     FROM crm_oportunidades o JOIN crm_etapas e ON e.id=o.etapa
    WHERE e.es_abierta)                                        AS oportunidades_abiertas,
  (SELECT COALESCE(SUM((o.cuota_mensual*12 + o.pago_unico) * e.probabilidad),0)
     FROM crm_oportunidades o JOIN crm_etapas e ON e.id=o.etapa
    WHERE e.es_abierta)                                        AS prevision_ponderada,
  (SELECT COUNT(*) FROM crm_seguimiento WHERE urgencia='vencida')          AS seguimiento_vencido,
  (SELECT COUNT(*) FROM crm_seguimiento WHERE urgencia='sin_seguimiento')  AS sin_seguimiento,
  (SELECT COALESCE(SUM(cuota_mensual),0) FROM crm_oportunidades
    WHERE etapa='ganado' AND date_trunc('month',cerrada_en)=date_trunc('month',CURRENT_DATE))
                                                               AS ganado_mes_mensual,
  (SELECT COALESCE(SUM(pago_unico),0) FROM crm_oportunidades
    WHERE etapa='ganado' AND date_trunc('month',cerrada_en)=date_trunc('month',CURRENT_DATE))
                                                               AS ganado_mes_unico;
